### ISSUE TITLE
ctrl c ctrl v

### ISSUE THREAD

**Issue by HolaMundo42** [Santiresnik/AkinatOrt#2]
while(true)
{
  if()
  {if()
  {if()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {}
}
}
 }
  else()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {}
}
}
 }
  else()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {}
}
}
}
}
 }
  else()
  {if()
  { }
  else()
  {if()
  { }
  else()
  {if()
  {if()
  { }
  else()
  {}
 }
  else()
  {}
}
}
}
}

**Comment by luc0x** [comment]
while(true){
   openDB();
}
